### PR TITLE
Spinner - new component initial setup.

### PR DESCRIPTION
**Pull request by MaximFedarau**
Created new component - Spinner.
Added props and set up Spinner in Storybook (docs and playground).

### CODE REVIEW

**Comment by MaximFedarau** [comment]
@harish-sethuraman

**Comment by MaximFedarau** [comment]
@amalkrishna

**Comment by MaximFedarau** [comment]
@harish-sethuraman

**Comment by harish-sethuraman** [comment]
Thanks for sending an PR. However do not have priority on adding newer components without design team's input. We really appreciate the time taken. Please make sure you raise an `issue` before sending an PR to confirm with the maintainer if it is feasible or not.

**Pull request closed without merging**
